### PR TITLE
fix: output kafka_brokers_sasl

### PR DESCRIPTION
**Pull request by JunliWang**
### Description

this [PR](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/323) was not correct 
`instance.extensions` is a map, `kafka_brokers_sasl` is a list inside the map, terraform has flatten this list into 
 kafka_brokers_sasl.0,  kafka_brokers_sasl.1, etc when output this map, so key `kafka_brokers_sasl` does not exist in the map.
 
 the fix is iterate the number of brokers to get correct keys from the map and construct the list.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by JunliWang** [comment]
the output looks good to me from the test

```
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: Outputs:
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: 
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: crn = "crn:v1:bluemix:public:messagehub:us-south:a/abac0df06b644a9cabc6e44f55b3880e:aa75d564-f802-4b16-ad65-2f157e7e2120::"
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: guid = "aa75d564-f802-4b16-ad65-2f157e7e2120"
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: kafka_broker_version = "3.6"
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: kafka_brokers_sasl = [
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66:   "broker-3-y8042l7vftjcsnwd.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66:   "broker-5-y8042l7vftjcsnwd.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66:   "broker-0-y8042l7vftjcsnwd.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66:   "broker-4-y8042l7vftjcsnwd.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66:   "broker-2-y8042l7vftjcsnwd.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66:   "broker-1-y8042l7vftjcsnwd.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: ]
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: kafka_http_url = "https://y8042l7vftjcsnwd.svc03.us-south.eventstreams.cloud.ibm.com/"
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: resource_group_id = "edbac64c0068438fa9ff19665d648f64"
TestRunQuickstartSolution 2024-11-18T17:56:45Z logger.go:66: resource_group_name = "geretain-test-event-streams"
TestRunQuickstartSolution 2024-11-18T17:56:45Z tests.go:880: FINISHED: Init / Apply
```

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
