### PR TITLE
fix: extend timeout

### PR DESCRIPTION
**Pull request by jor2**
### Description

Extend timeout as test failure due to provision timeout.
https://github.ibm.com/GoldenEye/issues/issues/5530

### Release required?
Identify the type of release. For information about the changes in a semantic versioning release, see [Release versioning](https://terraform-ibm-modules.github.io/documentation/#/versioning).

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version.

Your notes help the merger write the commit message for the PR that is published in the release notes for the module.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by ocofaigh** [comment]
@jor2 4 hours seems too long to wait. Did you confirm that some instance took longer than 3 hours to come up?

**Comment by jor2** [comment]
Maybe there was some server issues on the day but I seen in the logs
````
│ Error: [ERROR] Error waiting for create resource instance (crn:v1:bluemix:public:messagehub:us-south:a/abac0df06b644a9cabc6e44f55b3880e:5038a24d-836d-473d-bea1-cda94e5314d6::) to be succeeded: timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 3h0m0s)
````

And when I looked at the instance on the command line I seen `"create_time": 0,` in the json. I figured maybe because this was an enterprise instance it may have taken over 3 hours to provision, but perhaps if we don't see this issue again we can write to down to there being an issue with this one instance provisioning.

**Comment by ocofaigh** [comment]
@jor2 Do you have the full json from this instance still by any chance?

**Comment by ocofaigh** [comment]
Hmm, not much use. Looking at the logs, the 3 hour timeout occurred at `2023-08-03T08:11:15Z` but the JSON says `"created_at": "2023-08-03T05:11:15.628207273Z"` which is before the timeout :/
Lets close it for now, but if it happens again, we should keep a hold of the instance and create a support case to see why it took so long, and if they recommend to increase the timeout.

**Pull request closed without merging**
