### PR TITLE
use parameters_json for provision parameters

### PR DESCRIPTION
**Pull request by JunliWang**
### Description

contribute to: https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/issues/322
in order to support more complex provision parameters like mirroring. 
eg. 
```tf
parameters_json = jsonencode(
    {
      mirroring = {
        source_crn   = data.ibm_resource_instance.es_instance_source.id
        source_alias = "source-alias"
        target_alias = "target-alias"
        options = {
          topic_name_transform = {
             type = "rename" 
             rename = {
               add_prefix = "add_prefix"
               add_suffix = "add_suffix"
               remove_prefix = "remove_prefix"
               remove_suffix = "remove_suffix"
             }
          }
          group_id_transform = {
            type = "rename" 
            rename = {
              add_prefix = "add_prefix"
              add_suffix = "add_suffix"
              remove_prefix = "remove_prefix"
              remove_suffix = "remove_suffix"
            }
          }
        }
      }
    }
  )
  ```

### Release required?

this change is not a feature or fix, and it is transparent to users.
and it is a prerequisite for adding mirroring support: https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/324 which will be a new release.

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by JunliWang** [comment]
I used comment `SKIP UPGRADE TEST` to skip the upgrade test because standard plan instance does not support update parameters.

**Comment by JunliWang** [comment]
I did manual test with provider code, switching from `parameters` to `parameters_json` for Enterprise instance will update the instance in-place.
but I do not understand why the test in this module tests updating parameters for Standard instance, which does not support any provision/update parameters.

**Comment by ocofaigh** [comment]
@JunliWang Yea it seems the parameters were being passed regardless of what plan was used. But I guess the service was just ignoring them. Since this update is non disruptive, I approve this PR

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
